# lovelace_gen

type: custom:multiple-entity-row
entity: {{ entity }}
name: {{ name }}
icon: {{ icon | default('') }}
secondary_info: {{ secondary_info | default('') }}
tap_action:
  action: {{ tap_action | default('call-service') }}
  service: browser_mod.popup
  service_data:
    title: {{ name }}
    card:
      type: entities
      entities:
        - entity: {{ entity }}
          name: ' '
          icon: {{ icon | default('') }}
    deviceID:
      - this
    style:
      font-family: Oswald
      font-size: 14px
      border-radius: 1em
      box-shadow: 0em 0em 0.5em
      opacity: 0.9
style: >
  :host {
    margin-top: {{ margin_top | default ('') }};
    margin-bottom: {{ margin_bottom | default ('') }};
  }

