
#=========================
#=== TEMPERATURE SETTINGS
#=========================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== Temperature Settings
      - !include
          - ../../../titles.yaml
          - title: TEMPERATURE SETTINGS
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_top: -1em
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== Number of days to use
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_temp_history_used
            name: Number of days data to use
            label: (0 to 4) If zero only the temperature today is used

      #=== Temperature Baseline
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temperature_baseline
            name: Baseline temperature
            label: Exceeding this temperature increases the watering time
            unit: °C

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------

      #=== Temperature Data
      - !include
          - ../../../titles.yaml
          - title: TEMPERATURE DATA
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== Temperature Multiplier
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_temp_multiplier
            name: Multiplier used in calculations
            label: Calculated based on temperature and baseline
            round: 2
            tap_action: none

      #=== Actual High Temperature
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_actual_high_temp_0
            name: High temperature today (Actual)
            round: 1
            unit: °C
            tap_action: none

      #=== Forecast High Temperature
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.dark_sky_forecast_daytime_high_temperature_0d
            name: High temperature today (Forecast)
            round: 1
            unit: °C
            tap_action: none


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Forecast vs. Actual High Temperature
      - !include
          - ../../../titles.yaml
          - title:  HIGH TEMPERATURE - <font color=IndianRed>Forecast</font> vs. <font color=SteelBlue>Actual</font>
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_bottom: -1.5em
            border_left_color: var(--accent-color)

      #=== Forecast vs. Actual High Temperature Graph
      - !include item_settings_temperature_graph.yaml

      #=== Use Forecast High Temperature
      - !include item_settings_use_forecast_high_temp.yaml


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Temperature History
      - !include
          - ../../../titles.yaml
          - title: TEMPERATURE HISTORY
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== High Temperature Yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_1
            name: Yesterday
            round: 1
            unit: °C
            tap_action: none
            padding: 0.5em 0em 0.5em 0em

      #=== High Temperature 2 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_2
            name: Two days ago
            round: 1
            unit: °C
            tap_action: none

      #=== High Temperature 3 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_3
            name: Three days ago
            round: 1
            unit: °C
            tap_action: none

      #=== High Temperature 4 Days Ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_high_temp_4
            name: Four days ago
            unit: °C
            round: 1
            tap_action: none

style: >
  ha-card {
    box-shadow: none;
  }
