
#=====================
#=== GENERAL SETTINGS
#=====================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== Irrigation Master Control and Testing Mode
      - type: horizontal-stack
        cards:

          #=== Irrigation Master Control switch
          - !include
            - ../item_settings_check_box_with_entity_icon.yaml
            - entity: input_boolean.irrigation_master_control_switch
              on_name: "System is ON"
              off_name: "System is OFF"

          #=== Irrigation Testing Mode
          - !include
            - ../item_settings_check_box_with_entity_icon.yaml
            - entity: input_boolean.irrigation_testing_mode

      #=== Testing mode warning
      - !include item_settings_test_mode_warning.yaml

      #=== Notify users
      - !include item_settings_notify_users.yaml

      #=== Edit user names
      - !include item_settings_edit_user_names.yaml


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== UI Font
      - type: custom:button-card
        entity: input_text.irrigation_ui_font_family
        show_state: true
        name: User interface font
        size: 30%
        styles:
          grid:
            - grid-template-areas: '"i n s"  "i n s"'
            - grid-template-columns: 15% auto 15%
            - grid-template-rows: min-content min-content
          card:
            - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
            - font-size: 15px
            - padding: 0em 0em 0.5em 0em
            - background: none
            - box-shadow: none
          name: 
            - justify-self: start
          label:
            - justify-self: start
            - color: var(--secondary-text-color)
        tap_action:
          action: call-service
          service: browser_mod.popup
          service_data:
            title: User Interface Font
            card:
              type: vertical-stack
              cards:
                - type: markdown
                  content: Leave blank to use the font from the current theme.
                  style: >
                    ha-card {
                      box-shadow: none;
                      padding: 0em 0em 0em 1em;
                      background: var(--paper-dialog-background-color);
                      margin: 0em;
                    }
                    p {
                      font-size: 18px;
                    }
                - type: entities
                  entities:
                    - entity: input_text.irrigation_ui_font_family
                      name: Font Name
                  style: >
                    ha-card {
                      box-shadow: none;
                      border-radius: 0em 0em 1em 1em;
                      background: var(--paper-dialog-background-color);
                    }
            deviceID:
              - this
            style:
              font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
              box-shadow: 0em 0em 0.5em
              border-radius: 1em
              opacity: 0.9

      #=== Weather Sensors
      - type: custom:button-card
        name: Weather Sensors...
        icon: mdi:weather-partly-cloudy
        show_state: true
        state_display: <elt><ha-icon icon=mdi:square-edit-outline></ha-icon></elt>
        styles:
          grid:
            - grid-template-areas: '"i n s"'
            - grid-template-columns: 15% auto 5%
            - grid-template-rows: 1fr
          card:
            - height: 2em
            - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
            - font-size: 15px
            - padding: 0em 1.5em 0.5em 0.2em
            - background: none
            - box-shadow: none
          name: 
            - justify-self: start
        tap_action:
          action: call-service
          service: browser_mod.popup
          service_data:
            title: Weather Sensors
            card:
              type: vertical-stack
              cards:
                - type: markdown
                  content: >
                    For the Weather Outlook you need to create the following sensor:


                    <span>sensor.irrigation_weather_outlook</span>


                    Leave any of the following sensors blank to reset to default.
                  style: >
                    ha-card {
                      box-shadow: none;
                      padding: 0em 0em 0em 1em;
                      background: var(--paper-dialog-background-color);
                      margin: 0em;
                    }
                    span {
                      display: block;
                      text-align: center;
                      font-family: roboto;
                      font-size: 14px;
                    }
                    p {
                      font-size: 18px;
                    }
                - type: entities
                  entities:
                    - type: section
                      label: Rainfall Sensors
                    - entity: input_text.irrigation_external_sensor_rainfall_today
                      name: Rain Today
                    - entity: input_text.irrigation_external_sensor_rainfall_yesterday
                      name: Rain Yesterday
                    - entity: input_boolean.irrigation_show_smartweather_stations
                      name: Using SmartWeather (show stations)
                    - type: section
                      label: Temperature Sensors
                    - entity: input_text.irrigation_external_sensor_forecast_high_temp
                    - entity: input_text.irrigation_external_sensor_current_temp
                    # - type: section
                  style: >
                    ha-card {
                      box-shadow: none;
                      border-radius: 0em 0em 1em 1em;
                      background: var(--paper-dialog-background-color);
                    }
                # - type: markdown
                #   content: >
                #     You must also create a sensor to provide the Weather Outlook:


                #     <span>sensor.irrigation_weather_outlook</span>
                #   style: >
                #     ha-card {
                #       box-shadow: none;
                #       padding: 0em 0em 0em 1em;
                #       background: var(--paper-dialog-background-color);
                #       margin: 0em;
                #     }
                #     span {
                #       display: block;
                #       text-align: center;
                #       font-family: roboto;
                #       font-size: 14px;
                #     }
                #     p {
                #       font-size: 18px;
                #     }
            deviceID:
              - this
            style:
              font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
              box-shadow: 0em 0em 0.5em
              border-radius: 1em
              opacity: 0.9

      #=== Number of zones
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_number_of_zones
            name: Number Of Zones

      #=== Minimum duration when using weather adjustments
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_weather_adjusted_minimum_duration_in_seconds
            name: Minimum Time To Run A Zone
            label: When using weather adjustments

      #=== Maximum duration when using weather adjustments
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_weather_adjusted_maximum_duration_in_minutes
            name: Maximum Time To Run A Zone
            label: When using weather adjustments


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Irigation controller WiFi signal strength
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.esphome_irrigation_controller_wifi_signal
            name: Irrigation Controller WiFi Signal Strength
            tap_action: none
            padding: 0.5em 0em 0.5em 0em

style: >
  ha-card {
    box-shadow: none;
  }
