
#=== HELP BUTTON
type: custom:button-card
icon: mdi:information-outline
show_name: false
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: "\U00002139 INFORMATION"
    card:
      type:  markdown
      content: >
        Tap a Cycle Start Time to edit the schedule time

        Tap a Cycle header to edit the name


        Tap a Zone to edit its information


        ---



        * #### Adjust For Weather (Experimental)

        Turning on weather adjustments will adjust watering time based on temperature
        and/or rainfall. See Settings.



        ---


        * #### Rain multiplier
        
        This multiplier will decrease watering time proportionally
        based on the difference between the rainfall threshold and the amount of
        rain over the last few days. If the threshold is reached then it will
        stop it altogether.


        ---


        * #### Temperature multiplier

        This multiplier will increase or decrease watering time proportionally
        based on the difference between the temperature threshold and the 
        average high temperature over the last few days.

        It is calculated as High Temperature divided by Baseline Temperature.

        For example, if the baseline temperature is set to 25 degrees and the
        average temperature has been 30 degrees the adjustent will be plus 20%.
        Likewise if the average temperature has only been 20 degrees the
        adjustment will be minus 20%.

        </font>
    deviceID:
      - this
    style:
      font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
      font-size: 14px
      box-shadow: 0em 0em 0.5em
      opacity: 0.9
styles:
  card:
    - background: none
    - height: 35px
    - width: 45px
    - border-radius: 10px
    - box-shadow: "0px 0px 0px 0px"
  icon:
    - width: 45px
    - color: var(--accent-color)
