# lovelace_gen

#==================
#=== SETTINGS LINE
#==================
type: custom:button-card
entity: {{ entity }}
show_state: true
state_display: >
  [[[
    var unit = '{{ unit }}';
    var round = '{{ round }}';
    var statestr = entity.state;
    
    if (isNaN(statestr))
      return statestr;
    else if(unit.length > 0)
      return parseFloat(statestr).toFixed(round) + unit;
    else
      return parseFloat(statestr).toFixed(round);
  ]]]
name: {{ name }}
icon: {{ icon }}
show_label: true
label: {{ label }}
size: 30%
tap_action:
  action: {{ tap_action | default('call-service') }}
  service: browser_mod.popup
  service_data:
    title: {{ name }}
    card:
      type: entities
      entities:
        - entity: {{ entity }}
          name: ' '
          icon: {{ icon }}
    deviceID:
      - this
    style:
      font-family: >
        [[[
          return states['input_text.irrigation_ui_font_family'].state
        ]]]
      box-shadow: 0em 0em 0.5em
      opacity: 0.9
styles:
  grid:
    - grid-template-areas: >
        [[[
          if ('{{ label }}' == '')
            return '"i n s"  "i n s"';
          else
            return '"i n s"  "i l s"';
        ]]]
    - grid-template-columns: 15% auto 15%
    - grid-template-rows: min-content min-content
  card:
    - font-size: 14px
    - padding: {{ padding | default('0em 0em 0.5em 0em') }}
    - box-shadow: none
  name: 
    - justify-self: start
  label:
    - justify-self: start
    - color: var(--secondary-text-color)
