# lovelace_gen

#===================================
#=== SMARTWEATHER STATION CHECK BOX
#===================================
type: custom:button-card
entity: {{ entity }}
name: {{ name }}
icon: mdi:check-box-outline
size: 100%
styles:
  grid:
    - grid-template-areas: '"n i"'
    - grid-template-columns: '1fr 25%'
  card:
    - height: 3.5em
    - margin-top: -0.1em
    - font-size: 14px
    - box-shadow: none
  name:
    - justify-self: right
state:
  - value: 'off'
    icon: mdi:checkbox-blank-outline
    styles:
      card:
        - color: var(--secondary-text-color)
        - opacity: 50%
      icon:
        - color: var(--secondary-text-color)
