
#======================
#=== RAINFALL SETTINGS
#======================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== General Rainfall Settings
      - !include
          - ../../../titles.yaml
          - title: GENERAL RAINFALL SETTINGS
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_top: -1em
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== Number of days history
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_rainfall_history_used
            name: Number of days history to use
            secondary_info: (0 to 4) If zero only rainfall today is used
            round: 0

      #=== Rainfall threshold
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_threshold
            name: Rainfall threshold
            secondary_info: If this threshold is reached no watering takes place


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Percentage Of Rainfall To Include
      - !include
          - ../../../titles.yaml
          - title: RAINFALL INCLUDED IN CALCULATIONS
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_top: -0.5em
            margin_bottom: -1.5em
            border_left_color: var(--accent-color)

      #=== Yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_1
            name: Yesterday

      #=== Two days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_2
            name: Two days ago
            margin_top: -0.5em

      #=== Three days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_3
            name: Three days ago
            margin_top: -0.5em

      #=== Four days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_4
            name: Four days ago
            margin_top: -0.5em


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Rainfall Data
      - !include
          - ../../../titles.yaml
          - title: RAINFALL DATA
            font_size: 18px
            font_family: Oswald
            color: var(--secondary-text-color)
            margin_top: -0.5em
            margin_bottom: -1em
            border_left_color: var(--accent-color)

      #=== Multiplier used in calculations
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_multiplier
            name: Multiplier used in calculations
            secondary_info: Calculated based on rainfall and threshold
            tap_action: none

      #=== The average of all Smartweather sensors
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.smartweather_average_rain_today
            name: Rainfall today
            secondary_info: The average of all Smartweather sensors
            icon: mdi:weather-rainy
            tap_action: none

      #=== Rainfall yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_1
            name: Rainfall Yesterday
            tap_action: none

      #=== Rainfall two days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_2
            name: Two days ago
            tap_action: none
            margin_top: -0.5em

      #=== Rainfall three days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_3
            name: Three days ago
            tap_action: none
            margin_top: -0.5em

      #=== Rainfall four days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_4
            name: Four days ago
            tap_action: none
            margin_top: -0.5em

      #=== SmartWeather Stations Used
      - !include item_settings_smartweather_stations_used.yaml

style: >
  ha-card {
    margin-top: -0.75em;
  }
