
#===================
#=== Input Booleans
#===================
input_boolean:

  #======================
  #=== Show Cycles in UI
  #======================
  irrigation_ui_show_cycle1:
    name: Show Cycle 1

  irrigation_ui_show_cycle2:
    name: Show Cycle 2

  irrigation_ui_show_cycle3:
    name: Show Cycle 3

  #========================
  #=== Show Settings in UI
  #========================
  irrigation_ui_show_general_settings:
    name: General

  irrigation_ui_show_rainfall_settings:
    name: Rainfall

  irrigation_ui_show_temperature_settings:
    name: Temperature

  #====================================
  #=== Show History and Last Run in UI
  #====================================
  irrigation_ui_show_last_run_details:
    name: Last Run

  irrigation_ui_show_status_history:
    name: Status History


#============
#=== Sensors
#============
sensor:
  - platform: template
    sensors:
      irrigation_ui_selected_cycle:
        value_template: >
          {% if is_state('input_boolean.irrigation_ui_show_cycle1', 'on') %}   
            cycle1
          {% elif is_state('input_boolean.irrigation_ui_show_cycle2', 'on') %}   
            cycle2
          {% elif is_state('input_boolean.irrigation_ui_show_cycle3', 'on') %}   
            cycle3
          {% else %}
            no cycle selected
          {% endif %}

      irrigation_ui_selected_settings:
        value_template: >
          {% if is_state('input_boolean.irrigation_ui_show_general_settings', 'on') %}   
            general
          {% elif is_state('input_boolean.irrigation_ui_show_rainfall_settings', 'on') %}   
            rainfall
          {% elif is_state('input_boolean.irrigation_ui_show_temperature_settings', 'on') %}   
            temperature
          {% else %}
            no settings selected
          {% endif %}


#================
#=== Automations
#================
automation:

  #======================================
  #=== SET UI DEFAULTS WHERE APPROPRIATE
  #======================================
  #=========
  #=== Font
  #=========
  - alias: Irrigation UI Set Default Font
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_ui_font_family
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_ui_font_family
          value: Oswald


  #============
  #=== CYCLE 1
  #============
  - alias: Irrigation UI Set Default Cycle 1 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_cycle1_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_cycle1_name
          value: Morning Cycle


  #============
  #=== CYCLE 2
  #============
  - alias: Irrigation UI Set Default Cycle 2 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_cycle2_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_cycle2_name
          value: Afternoon Cycle


  #============
  #=== CYCLE 3
  #============
  - alias: Irrigation UI Set Default Cycle 3 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_cycle3_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_cycle3_name
          value: Manual Cycle


  #=============================
  #=== SECTION HEADER SELECTION
  #=============================
  #=====================
  # Show Selected Cycle
  #=====================
  - alias: Irrigation UI Show Selected Cycle
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_cycle1
          - input_boolean.irrigation_ui_show_cycle2
          - input_boolean.irrigation_ui_show_cycle3
        to: 'on'

    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {% if 'cycle1' in trigger.entity_id %}   
              input_boolean.irrigation_ui_show_cycle2,
              input_boolean.irrigation_ui_show_cycle3
            {% elif 'cycle2' in trigger.entity_id %}
              input_boolean.irrigation_ui_show_cycle1,
              input_boolean.irrigation_ui_show_cycle3
            {% else %}
              input_boolean.irrigation_ui_show_cycle1,
              input_boolean.irrigation_ui_show_cycle2
            {% endif %}


  #===========================
  # Prevent No Selected Cycle
  #===========================
  - alias: Irrigation UI Prevent No Selected Cycle
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_cycle1
          - input_boolean.irrigation_ui_show_cycle2
          - input_boolean.irrigation_ui_show_cycle3
        to: 'off'

    condition:
      - condition: state
        entity_id: input_boolean.irrigation_ui_show_cycle1
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_cycle2
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_cycle3
        state: 'off'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {{ trigger.entity_id }}


  #========================
  # Show Selected Settings
  #========================
  - alias: Irrigation UI Show Selected Settings
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_general_settings
          - input_boolean.irrigation_ui_show_rainfall_settings
          - input_boolean.irrigation_ui_show_temperature_settings
        to: 'on'

    action:
      - service: input_boolean.turn_off
        data_template:
          entity_id: >
            {% if 'general' in trigger.entity_id %}   
              input_boolean.irrigation_ui_show_rainfall_settings,
              input_boolean.irrigation_ui_show_temperature_settings
            {% elif 'rainfall' in trigger.entity_id %}
              input_boolean.irrigation_ui_show_general_settings,
              input_boolean.irrigation_ui_show_temperature_settings
            {% else %}
              input_boolean.irrigation_ui_show_general_settings,
              input_boolean.irrigation_ui_show_rainfall_settings
            {% endif %}


  #==============================
  # Prevent No Selected Settings
  #==============================
  - alias: Irrigation UI Prevent No Selected Settings
    trigger:
      - platform: state
        entity_id:
          - input_boolean.irrigation_ui_show_general_settings
          - input_boolean.irrigation_ui_show_rainfall_settings
          - input_boolean.irrigation_ui_show_temperature_settings
        to: 'off'

    condition:
      - condition: state
        entity_id: input_boolean.irrigation_ui_show_general_settings
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_rainfall_settings
        state: 'off'

      - condition: state
        entity_id: input_boolean.irrigation_ui_show_temperature_settings
        state: 'off'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {{ trigger.entity_id }}


  #=============================================================
  #=== Show relevent Settings page when adjustment is turned on
  #=============================================================
  - alias: Irrigation UI Show Weather Adjust Settings
    trigger:
      - platform: state
        entity_id: 
          - input_boolean.irrigation_cycle1_adjust_for_rainfall
          - input_boolean.irrigation_cycle2_adjust_for_rainfall
          - input_boolean.irrigation_cycle1_adjust_for_temperature
          - input_boolean.irrigation_cycle2_adjust_for_temperature
        to: 'on'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {% if 'rainfall' in trigger.entity_id %}
              input_boolean.irrigation_ui_show_rainfall_settings
            {% else %}
              input_boolean.irrigation_ui_show_temperature_settings
            {% endif %}

  #=== END OF SECTION HEADER SELECTION BUTTONS


  #==========================
  #=== DAY SELECTION BUTTONS
  #==========================
  #=============================================
  #=== 'Every Day' selected so turn All Days on
  #=============================================
  - alias: Irrigation UI Cycle1 Selection Control Every Day
    trigger: 
      - platform: state
        entity_id: 
          - input_boolean.irrigation_cycle1_every_day
          - input_boolean.irrigation_cycle2_every_day
        to: 'on'

    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >
            {% set cycle = 'cycle1' if 'cycle1' in trigger.entity_id else 'cycle2' %}            
            input_boolean.irrigation_{{ cycle }}_mon,
            input_boolean.irrigation_{{ cycle }}_tue,
            input_boolean.irrigation_{{ cycle }}_wed,
            input_boolean.irrigation_{{ cycle }}_thu,
            input_boolean.irrigation_{{ cycle }}_fri,
            input_boolean.irrigation_{{ cycle }}_sat,
            input_boolean.irrigation_{{ cycle }}_sun


  #=============================
  #=== Day button selected
  #=== If all days are selected
  #=== Turn on 'Every Day'
  #=== Else off 'Every Day'
  #=============================
  - alias: Irrigation UI Cycle Day Button
    trigger: 
      - platform: state
        entity_id:
          - input_boolean.irrigation_cycle1_mon
          - input_boolean.irrigation_cycle1_tue
          - input_boolean.irrigation_cycle1_wed
          - input_boolean.irrigation_cycle1_thu
          - input_boolean.irrigation_cycle1_fri
          - input_boolean.irrigation_cycle1_sat
          - input_boolean.irrigation_cycle1_sun

          - input_boolean.irrigation_cycle2_mon
          - input_boolean.irrigation_cycle2_tue
          - input_boolean.irrigation_cycle2_wed
          - input_boolean.irrigation_cycle2_thu
          - input_boolean.irrigation_cycle2_fri
          - input_boolean.irrigation_cycle2_sat
          - input_boolean.irrigation_cycle2_sun

    action:
      - service_template: >
          {% if trigger.to_state.state == 'on' %}
            {% set cycle = 'cycle1' if 'cycle1' in trigger.entity_id else 'cycle2' %}            
            {% if is_state('input_boolean.irrigation_' ~ cycle ~ '_mon', 'on') and
                  is_state('input_boolean.irrigation_' ~ cycle ~ '_tue', 'on') and
                  is_state('input_boolean.irrigation_' ~ cycle ~ '_wed', 'on') and
                  is_state('input_boolean.irrigation_' ~ cycle ~ '_thu', 'on') and
                  is_state('input_boolean.irrigation_' ~ cycle ~ '_fri', 'on') and
                  is_state('input_boolean.irrigation_' ~ cycle ~ '_sat', 'on') and
                  is_state('input_boolean.irrigation_' ~ cycle ~ '_sun', 'on') %}
              input_boolean.turn_on
            {% else %}
              input_boolean.turn_off
            {% endif %}
          {% else %}
              input_boolean.turn_off
          {% endif %}
        data_template:
          entity_id: >
            {% set cycle = 'cycle1' if 'cycle1' in trigger.entity_id else 'cycle2' %}            
            input_boolean.irrigation_{{ cycle }}_every_day

  #=== END OF DAY SELECTION BUTTONS


  #==========================
  #=== ZONE DURATION CHANGES
  #==========================
  #======================================================
  #=== If a duration is set to zero turn on Skip
  #=== If a duration changes to above zero turn off Skip
  #======================================================
  - alias: Irrigation UI Zone Duration To Or From Zero
    trigger:
      - platform: state
        entity_id:
          - input_number.irrigation_cycle1_zone1_duration
          - input_number.irrigation_cycle1_zone2_duration
          - input_number.irrigation_cycle1_zone3_duration
          - input_number.irrigation_cycle1_zone4_duration
          - input_number.irrigation_cycle1_zone5_duration
          - input_number.irrigation_cycle1_zone6_duration
          - input_number.irrigation_cycle1_zone7_duration
          - input_number.irrigation_cycle1_zone8_duration

          - input_number.irrigation_cycle2_zone1_duration
          - input_number.irrigation_cycle2_zone2_duration
          - input_number.irrigation_cycle2_zone3_duration
          - input_number.irrigation_cycle2_zone4_duration
          - input_number.irrigation_cycle2_zone5_duration
          - input_number.irrigation_cycle2_zone6_duration
          - input_number.irrigation_cycle2_zone7_duration
          - input_number.irrigation_cycle2_zone8_duration

    action:
      - service_template: >
          {% if trigger.to_state.state == '0.0' %}
            input_boolean.turn_on
          {% else %}
            input_boolean.turn_off
          {% endif %}
        data_template:
          entity_id: >
            {% set cycle = 'cycle1' if 'cycle1' in trigger.entity_id else 'cycle2' %}            
            {% set zone = 'zone1' if 'zone1' in trigger.entity_id else zone %}
            {% set zone = 'zone2' if 'zone2' in trigger.entity_id else zone %}
            {% set zone = 'zone3' if 'zone3' in trigger.entity_id else zone %}
            {% set zone = 'zone4' if 'zone4' in trigger.entity_id else zone %}
            {% set zone = 'zone5' if 'zone5' in trigger.entity_id else zone %}
            {% set zone = 'zone6' if 'zone6' in trigger.entity_id else zone %}
            {% set zone = 'zone7' if 'zone7' in trigger.entity_id else zone %}
            {% set zone = 'zone8' if 'zone8' in trigger.entity_id else zone %}
            
            input_boolean.irrigation_{{ cycle }}_{{ zone }}_skip


  #==================================================
  #=== Zone Duration updated
  #=== Keep input_number slider and box synchronised
  #==================================================
  - alias: Irrigation UI Duration Synchronisation
    trigger: 
      - platform: state
        entity_id:
          - input_number.irrigation_cycle1_zone1_duration
          - input_number.irrigation_cycle1_zone1_duration_box
          - input_number.irrigation_cycle1_zone2_duration
          - input_number.irrigation_cycle1_zone2_duration_box
          - input_number.irrigation_cycle1_zone3_duration
          - input_number.irrigation_cycle1_zone3_duration_box
          - input_number.irrigation_cycle1_zone4_duration
          - input_number.irrigation_cycle1_zone4_duration_box
          - input_number.irrigation_cycle1_zone5_duration
          - input_number.irrigation_cycle1_zone5_duration_box
          - input_number.irrigation_cycle1_zone6_duration
          - input_number.irrigation_cycle1_zone6_duration_box
          - input_number.irrigation_cycle1_zone7_duration
          - input_number.irrigation_cycle1_zone7_duration_box
          - input_number.irrigation_cycle1_zone8_duration
          - input_number.irrigation_cycle1_zone8_duration_box

          - input_number.irrigation_cycle2_zone1_duration
          - input_number.irrigation_cycle2_zone1_duration_box
          - input_number.irrigation_cycle2_zone2_duration
          - input_number.irrigation_cycle2_zone2_duration_box
          - input_number.irrigation_cycle2_zone3_duration
          - input_number.irrigation_cycle2_zone3_duration_box
          - input_number.irrigation_cycle2_zone4_duration
          - input_number.irrigation_cycle2_zone4_duration_box
          - input_number.irrigation_cycle2_zone5_duration
          - input_number.irrigation_cycle2_zone5_duration_box
          - input_number.irrigation_cycle2_zone6_duration
          - input_number.irrigation_cycle2_zone6_duration_box
          - input_number.irrigation_cycle2_zone7_duration
          - input_number.irrigation_cycle2_zone7_duration_box
          - input_number.irrigation_cycle2_zone8_duration
          - input_number.irrigation_cycle2_zone8_duration_box
          
          - input_number.irrigation_cycle3_zone1_duration
          - input_number.irrigation_cycle3_zone1_duration_box
          - input_number.irrigation_cycle3_zone2_duration
          - input_number.irrigation_cycle3_zone2_duration_box
          - input_number.irrigation_cycle3_zone3_duration
          - input_number.irrigation_cycle3_zone3_duration_box
          - input_number.irrigation_cycle3_zone4_duration
          - input_number.irrigation_cycle3_zone4_duration_box
          - input_number.irrigation_cycle3_zone5_duration
          - input_number.irrigation_cycle3_zone5_duration_box
          - input_number.irrigation_cycle3_zone6_duration
          - input_number.irrigation_cycle3_zone6_duration_box
          - input_number.irrigation_cycle3_zone7_duration
          - input_number.irrigation_cycle3_zone7_duration_box
          - input_number.irrigation_cycle3_zone8_duration
          - input_number.irrigation_cycle3_zone8_duration_box

    action:
      - service: input_number.set_value
        data_template:
          entity_id: >
            {% set cycle = 'cycle' ~ trigger.entity_id.split('cycle')[1][0] %}
            {% set zone = 'zone' ~ trigger.entity_id.split('zone')[1][0] %}
            {% if trigger.entity_id.endswith('box') %}
              input_number.irrigation_{{ cycle }}_{{ zone }}_duration
            {% else %}
              input_number.irrigation_{{ cycle }}_{{ zone }}_duration_box
            {% endif %}            
          value: >
            {% set cycle = 'cycle' ~ trigger.entity_id.split('cycle')[1][0] %}
            {% set zone = 'zone' ~ trigger.entity_id.split('zone')[1][0] %}
            {% if trigger.entity_id.endswith('box') %}
              {% set value = states('input_number.irrigation_' ~ cycle ~ '_' ~ zone ~ '_duration_box') | float %}
            {% else %}
              {% set value = states('input_number.irrigation_' ~ cycle ~ '_' ~ zone ~ '_duration') | float %}
            {% endif %}            
            {{ value }}
            
  #=== END OF ZONE DURATION CHANGES

