
#================
#=== Input Texts
#================
input_text:

  irrigation_external_sensor_controller_wifi:
    name: Irrigation Controller WiFi Signal Strength
    icon: mdi:wifi
    min: 0
    max: 100


#============
#=== Sensors
#============
sensor:
  - platform: template

    #=========================================================
    #=== Internal sensors that are based on the external ones
    #=== that have been user defined in the input texts.
    #===
    #=== These sensors are synchronised manually in an
    #=== automation when the external ones change
    #=========================================================
    sensors:
      irrigation_sensor_controller_wifi:
        entity_id:
          - input_text.irrigation_external_sensor_controller_wifi
        value_template: >
          {{ states(states('input_text.irrigation_external_sensor_controller_wifi')) }}
        icon_template: mdi:wifi
        unit_of_measurement: dB


#================
#=== Automations
#================
automation:

  #==============================================
  #=== Set default Controller WiFi Signal Sensor
  #==============================================
  - alias: Irrigation Set Default Controller WiFi Signal Sensor
    trigger:
      - platform: homeassistant
        event: start

      - platform: state
        entity_id: input_text.irrigation_external_sensor_controller_wifi
        to: ''

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_text.irrigation_external_sensor_controller_wifi
          state: 'unknown'

        - condition: state
          entity_id: input_text.irrigation_external_sensor_controller_wifi
          state: ''

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_external_sensor_controller_wifi
          value: sensor.esphome_irrigation_controller_wifi_signal


  #===============================================================
  #=== Initialise the Controller WiFi Signal Sensor when HA starts
  #===============================================================
  - alias: Irrigation Initialise Controller WiFi Signal Sensors
    trigger:
      - platform: homeassistant
        event: start

    action:
      - service: homeassistant.update_entity
        data:
          entity_id: 
            - sensor.irrigation_external_sensor_controller_wifi


  #===================================================
  #=== Synchronise the Zone Switch Sensors
  #=== These need to be updated as tehy are templated
  #=== on the switch name provided by through the UI
  #=== and are used in the history statistics sensors 
  #===================================================
  - alias: Irrigation Synchronise Sensor Zone Switches
    trigger:
      - platform: event
        event_type: state_changed

    condition:
      - condition: template
        value_template: >
          {{ 
            trigger.event.data.entity_id in [
              'input_text.irrigation_zone1_switch_entity_id',
              'input_text.irrigation_zone2_switch_entity_id',
              'input_text.irrigation_zone3_switch_entity_id',
              'input_text.irrigation_zone4_switch_entity_id',
              'input_text.irrigation_zone5_switch_entity_id',
              'input_text.irrigation_zone6_switch_entity_id',
              'input_text.irrigation_zone7_switch_entity_id',
              'input_text.irrigation_zone8_switch_entity_id',
              states('input_text.irrigation_zone1_switch_entity_id'),
              states('input_text.irrigation_zone2_switch_entity_id'),
              states('input_text.irrigation_zone3_switch_entity_id'),
              states('input_text.irrigation_zone4_switch_entity_id'),
              states('input_text.irrigation_zone5_switch_entity_id'),
              states('input_text.irrigation_zone6_switch_entity_id'),
              states('input_text.irrigation_zone7_switch_entity_id'),
              states('input_text.irrigation_zone8_switch_entity_id')
            ]
          }}

    action:
      - service: homeassistant.update_entity
        data_template:
          entity_id: >
            {% if 'zone1' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone1_switch
            {% elif 'zone2' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone2_switch
            {% elif 'zone3' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone3_switch
            {% elif 'zone4' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone4_switch
            {% elif 'zone5' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone5_switch
            {% elif 'zone6' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone6_switch
            {% elif 'zone7' in trigger.event.data.entity_id %}
              sensor.irrigation_sensor_zone7_switch
            {% else %}
              sensor.irrigation_sensor_zone8_switch
            {% endif %}


  # #===================================================================================
  # #=== Synchronise the sensor for the Controller WiFi Signal with the external sensor
  # #===================================================================================
  # - alias: Irrigation Synchronise Sensor WiFi Controller
  #   trigger:
  #     - platform: event
  #       event_type: state_changed

  #   condition:
  #     - condition: template
  #       value_template: >
  #         {{ 
  #           trigger.event.data.entity_id in [
  #             'input_text.irrigation_external_sensor_controller_wifi',
  #             states('input_text.irrigation_external_sensor_controller_wifi')
  #           ]
  #         }}

  #   action:
  #     - service: homeassistant.update_entity
  #       entity_id: sensor.irrigation_external_sensor_controller_wifi
